version: 2.1
orbs:
  node: circleci/node@4.2.0
  aws-cli: circleci/aws-cli@2.0.0
jobs:
  build:
    docker:
      - image: "cimg/base:stable"
  
   steps:
      - node/install
      - checkout
      - aws-cli/setup
      - run:
          name: Front-End Install
          command: |
            npm run frontend:install
      - run:
          name: Back-End Install
          command: |
            npm run backend:install
      - run:
          name: Front-End Build
          command: |
            npm run frontend:build
      - run:
          name: Back-End Build
          command: |
            npm run backend:build
      - run:
          name: Deploy App
          command: |
            npm run frontend:deploy

      # - run:
      #     name: Deploy Frontend
      #     command: aws s3 cp --recursive --acl public-read ./www $S3_BUCKET_FRONTEND
workflows:
  build_and_deploy:
    jobs:
      - frontend
      - server